apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-api1
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
        - name: api1
          image: marcelohaubrih/api-conversao:v1
          ports:
            - containerPort: 8080