apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-api2
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
        - name: api2
          image: marcelohaubrih/apidotnet-conversao:multi
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: api2
spec:
  selector:
    app: api2
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30002
  type: NodePort